### ISSUE TITLE
Modularize workflow

### ISSUE THREAD

**Issue by gipert** [legend-exp/legend-dataflow#23]
The main Snakefile would be more readable if we factor out parts:
```
Snakefile
rules/build_dsp.smk
rules/build_hit.smk
...
```
and then include them back with the Snakemake `include` directive.

**Comment by ggmarshall** [comment]
This is tricky as snakemake is not installed and all rules need access to the scripts dir so need a nice way to specify relative paths to modules

**Comment by gipert** [comment]
Uhm not sure what you mean, it works as expected in the simflow:

https://github.com/legend-exp/legend-simflow/blob/main/Snakefile#L307

**Comment by gipert** [comment]
Yes, it's really nothing more than a dumb paste of the code from the module into the Snakefile
