### ISSUE TITLE
Skm ideas/changes

### ISSUE THREAD

**Issue by ggmarshall** [legend-exp/legend-dataflow#34]

**Comment by ggmarshall** [comment]
skim out non-physics events
1 skimmed file per period

**Comment by ggmarshall** [comment]
add units

**Comment by gipert** [comment]
We need to converge on the list of cuts we want to apply to the event tier. Another problem: we cannot initialize LGDO Tables with nested Awkward record arrays at the moment. It's easy to implement but someone gotta do it.
