### ISSUE TITLE
Support specifying read-only paths to improve LH5 read performance

### ISSUE THREAD

**Issue by gipert** [legend-exp/legend-dataflow#40]
This would be useful at NERSC, since CFS is very slow. It's possible to read data from a read-only mount of the CFS storage (`/dvs_ro/common`) and this speeds up the data production by a lot. I think this can only be implemented inside the individual `build_*()` scripts though.

**Comment by ggmarshall** [comment]
would be simple to just add a flag I suppose in the scripts to sub the path

**Comment by gipert** [comment]
Like https://github.com/legend-exp/legend-simflow/commit/6fb163f26e3a6b2081780f3d559225fc60f31a58

**Comment by gipert** [comment]
Addressed in #53
