### ISSUE TITLE
check simultanous snakemake executions

### ISSUE THREAD

**Issue by mmatteo** [legend-exp/legend-dataflow#5]
Check whether multiple instances of snakemake can run at the same time sharing the .snakemake directory. This would be useful to process different data sets at the same time

**Comment by gipert** [comment]
In principle yes, I am doing this to process simulations separately in legend-simflow. But you need to make sure the sub-workflows are completely independent, otherwise Snakemake will detect this and fail.

**Comment by gipert** [comment]
https://snakemake.readthedocs.io/en/stable/executing/cli.html#dealing-with-very-large-workflows would be also useful to split the workflow into batches to be sent to different computing nodes (at e.g. NERSC)
